### PR TITLE
Added wrench peek view

### PR DESCRIPTION
**Pull request by mboperator**
screen shot 2016-01-26 at 10 45 00 am
screen shot 2016-01-26 at 11 57 42 am

### Notable Changes
- Added new Peek view that renders a WrenchIndicator (if the indicator exists on the window)

### :boom: [Peek Branch](https://github.com/procore/peek/pull/3)

### CODE REVIEW

**Comment by melch** [comment]
+1

**Comment by brock-noah** [comment]
+1

**Comment by thewillhuang** [comment]
+! :100:

**Comment by awseward** [comment]
+1

**Comment by awseward** [comment]
Might wanna add this to the `Procore Modifications` section in the README.

**Comment by dannyphillips** [comment]
+1

**Comment by mboperator** [comment]
Done, @awseward. Good call

**Comment by melch** [comment]
Merged. This branch passed testing as well.

**Pull request merged**
